# GPL License

language: python
cache:
  apt: true
  pip: true

python:
  # Use the Python version that comes with blender 2.79
  - "3.5.3"

before_install:
  - sudo apt-get update -qq
  # install blender from official sources.
  # This will most propably install an outdated blender version,
  # but it will resolve all system dependencies blender has to be able to run.
  - sudo apt-get install blender
  - sudo apt-get install unzip

install:
  # Then update blender
  - mkdir tmp && cd tmp
  - wget https://download.blender.org/release/Blender2.79/blender-2.79-linux-glibc219-x86_64.tar.bz2
  - tar jxf blender-2.79-linux-glibc219-x86_64.tar.bz2
  - mv blender-2.79-linux-glibc219-x86_64 blender

  - cd ..

  # Make sure to install mmd_tools plugin
  - wget https://github.com/powroupi/blender_mmd_tools/archive/dev_test.zip
  - unzip dev_test.zip
  - cd blender_mmd_tools-dev_test
  - mv mmd_tools/ ../tmp/blender/2.79/scripts/addons

  - cd ..

  # make sure to install cats plugin
  - sudo ln -s ${PWD} ${PWD}/tmp/blender/2.79/scripts/addons/cats

# Start unit testing
script:
  - python tests/run.py -b ./tmp/blender/blender -c True

notifications:
  webhooks:
    urls:
      - http://159.89.91.52:7778/webhook
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
